# Generated by Django 2.1.2 on 2018-11-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Natureza', 'Natureza'), ('Baby', 'Baby'), ('Religioso', 'Religioso'), ('Diversos', 'Diversos')], default='Diversos', max_length=10)),
                ('image', models.ImageField(upload_to='media')),
                ('titulo', models.CharField(max_length=20)),
                ('descritivo', models.CharField(max_length=30)),
            ],
        ),
    ]
