# Generated by Django 2.1.2 on 2018-11-12 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181108_1105'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='descritivo_foto',
            field=models.CharField(default=django.utils.timezone.now, max_length=70),
            preserve_default=False,
        ),
    ]
